Ecommerce/core/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    CartView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('cart/', CartView.as_view(), name='cart'),
    path('initiate-payment', views.initiate_payment, name="initiate-payment"),
    path('verify-payment/<str:ref>/', views.verify_payment, name="verify-payment"),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

Ecommerce/demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ecommerce/core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
import secrets
from .paystack import PayStack

# Create your models here.
CATEGORY_CHOICES = (
    ('BE', 'Beverage'),
    ('GS', 'Grains'),
    ('FZ', 'Frozen'),
    ('SI', 'Soupitems'),
    ('FR', 'Flour'),
    ('DH', 'Dryfish'),
    ('DF', 'Dryfruits')
)

LABEL_CHOICES = (
    ('S', 'sale'),
    ('N', 'new'),
    ('P', 'promotion')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Slide(models.Model):
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 500x500")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} - {}".format(self.caption1, self.caption2)

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    image_1 = models.ImageField()
    image_2 = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    #paid = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'BillingAddress', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'BillingAddress', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a BillingAddress
    (Failed Checkout)
    3. Payment
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    state = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'BillingAddresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    paystack_ref_id = models.CharField(max_length=150, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    email = models.EmailField()
    ref = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-timestamp",)

    def __str__(self) -> str:
        return f"{self.user.username} - {self.amount}"

    def save(self, *args, **kwargs):
        while not self.ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_ref = Payment.objects.filter(ref=ref).first()
            if not object_with_similar_ref:
                self.ref = ref
        super().save(*args, **kwargs)

    def amount_value(self):
        return self.amount * 100

    
    def verify_payment(self):
        paystack = PayStack()
        status, result = paystack.verify_payment(self.ref, self.amount)
        if status:
            self.paystack_response = result
            if result["amount"] / 100 == self.amount:
                self.completed = True
            self.save()
            return True
        return False

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

Ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "header.html" %}

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %} {% endblock %}
  <style type="text/css">
    .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
  </style>
  <body class="animsition">
    {% include "nav.html"%}
    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}

        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %} 
    {% endif %} 

    {% block content %} 
    {% endblock content %}

     {% block extra_body %} 
     {% endblock %} 

    {% include "footer.html"%} 
    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

Ecommerce/templates/footer.html
{% load static %}
<!-- ------------------------------footer sub end---------------------------------- -->
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Abel|Lato|Open+Sans&display=swap" rel="stylesheet">
<style>
  
    /* footer */
#footer-main{
	background: #000;
	color: white;
	font-size: 0.8rem;
	padding: 2.5rem 0;
    font-family: 'Lato', sans-serif;
}

#footer-main a{
	font-size: 14px;
	display: block;
	margin: 0.3rem;
	color: grey;
}

#footer-main a:hover{
	font-weight: bold;
	color: white;
}

#footer-main h6 a{
    color: white;

    
}



#footer-main hr {
    margin-top: 1rem;
    margin-bottom: 1rem;
    border: 0;
    border-top: 1px solid white;
}

#footer-main img{
	margin-right: 0.6rem;
}
</style>

<footer id="footer-main">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
            <br>

            <h6 class="mt-3"><a href="/">FIND A STORE</a></h6>
            <h6 class="mt-3"><a href="#">SIGN UP FOR EMAIL</a></h6>
            <h6 class="mt-3"><a href="{% url 'account_signup' %}">BECOME A MEMBER</h6>
            
            <h6 class="mt-3"><a href="/admin/">ADMIN LOGIN</a></h6>
           
        </div>

        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">GET HELP</a></h6>
            <a href="">Order Status</a>
            <a href="">Shipping and Delivery</a>
            <a href="">Returns</a>
            <a href="">Payment Options</a>
            <a href="">Contact Us</a>
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="#">ABOUT</a></h6>
            <a href="">News</a>
            <a href="">Careers</a>
            <a href="">Investors</a>
            <a href="">Sustainability</a>
            
            



        </div>
        <div class="col-sm-3">
          <a href="">Voice of Customer</a>
          <a href="">Contacts by Branch</a>
          <a href="">Ethics Reporting</a>
          <a href="">Careers</a>

          <br><br>
          <a href="">Business Inquiry</a>
       
          <br>
          <a href="#" class="ico"><i class="fab fa-apple fa-2x"></i> Apple Store</a>
          <a href="#" class="ico"><i class="fab fa-google-play fa-2x"></i> Google Play</a>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-6">
          
        </div>
        <div class="col-sm-6">
          
        </div>
        <hr>
        <a href="https://github.com/princevia" style="margin-left: 1rem">Privacy Policy </a>
      </div>
    </div>
  </footer>
<!-- ------------------------------footer end---------------------------------- -->

Ecommerce/templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% endblock content%}

Ecommerce/templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="topbar">
				<div class="topbar-social">
					<a href="https://facebook.com/viaexport/" class="topbar-social-item fab fa-facebook" target="_blank"></a>
					<a href="https://instagram.com/invites/contact/?i=1mawn61wva384&utm_content=nnxp6lf" target="_blank" class="topbar-social-item fab fa-instagram"></a>
					<!--
					<a href="#" class="topbar-social-item fab fa-pinterest-p"></a>
					<a href="#" class="topbar-social-item fab fa-twitter"></a>
					<a href="#" class="topbar-social-item fab fa-youtube"></a>
					-->
				</div>

				<span class="topbar-child1">
					Free local shipping for standard order over 300kg
				</span>

				<div class="topbar-child2">
					<span class="topbar-email">
						<a href="https://github.com/princevia">
						vialink929@gmail.com
					    </a>
					</span>

					<div class="topbar-language rs1-select2">
						<select class="selection-1" name="time">
							<option>NGN</option>
						</select>
					</div>
				</div>
			</div>

			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo">
					<img src="{% static 'images/vialink-removebg-preview.png' %}">
					<!-- <p style="color: black; "><b style="font-size: 22px;">V</b>IALINK<b style="font-size: 22px;">929</b></p> -->
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="/">Home</a>

							</li>

							<li>
								<a href="/shop/">Shop</a>
							</li>

							{% categories %}

							{% if request.user.is_authenticated %}
							<li>
								<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
							</li>
							<li>
								<a href="{% url 'account_logout' %}">Logout</a>
							</li>
							{% else %}
							<li>
								<a href="#">Login</a>
								<ul class="sub_menu">
									<li><a href="{% url 'account_login' %}">Login</a></li>
									<li><a href="{% url 'account_signup' %}">SignUp</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>

				<!-- Header Icon -->
				<div class="header-icons">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide1"></span>
					<!--
					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						 Header cart noti -->
						<!-- 
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											White Shirt With Pleat Detail Back
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>
							 

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									-->
									<!-- Button 
									<a href="{% url 'core:order-summary' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>
								
								<div class="header-cart-wrapbtn">
									-->
									<!-- Button 
									<a href="/payment/" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
								-->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="{% url 'core:home' %}" class="logo-mobile">
				<img src="{% static 'images/vialink-removebg-preview.png' %}" alt="IMG-LOGO">
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<!--
									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											White Shirt With Pleat Detail Back
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>
						
							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									-->
									<!-- Button 
									<a href="{% url 'core:order-summary' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									-->
									<!-- Button 
									<a href="/payment/" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
								-->
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free local shipping for standard order over 300kg
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								vialink929@gmail.com
							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>NGN</option>
								</select>
							</div>
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="https://facebook.com/viaexport/" target="_blank" class="topbar-social-item fa fa-facebook"></a>
							<a target="_blank" href="https://instagram.com/invites/contact/?i=1mawn61wva384&utm_content=nnxp6lf" class="topbar-social-item fa fa-instagram"></a>
							<!--
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
							-->
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

Ecommerce/templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}

    </style>

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">₦{{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-₦{{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (NGN)</span>
          <strong>₦{{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

Ecommerce/templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Qty</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
              ₦{{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ₦{{ order_item.get_amount_saved }}</span>
              {% else %}
              ₦{{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ₦{{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>₦{{ object.get_total }}</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
        		<a href="/" class="btn btn-primary float-right">Continue Shopping</a>

        	</td>
        </tr>
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% endblock content %}